apiVersion: v1
kind: ConfigMap
metadata:
  name: kavita
  labels:
    app: kavita
data:
  appsettings.json: |
    {
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kavita-email
  labels:
    app: kavita-email
data:
  # populate in overlay

