apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kavita

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
