apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kavita
  name: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <set this in overlay>
  storageClassName: local-path

