apiVersion: v1
kind: Service
metadata:
  name: kavita
  labels:
    name: kavita
spec:
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kavita
  #publishNotReadyAddresses: true

