apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:
  # Set the hostname for the Kavita ingress
  - target:
      version: v1
      kind: Ingress
      name: kavita
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kavita.local
      - op: add
        path: /spec/rules/-
        value:
          host: kavita.qed.fyi
          http:
            paths:
              - path: /
                backend:
                  service:
                    name: kavita
                    port:
                      name: http
                pathType: Prefix

  # Set the amount of storage to use for Kavita in its PVC
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: kavita
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi

  # Set the location of the library's volume in the Deployment
  - target:
      version: v1
      kind: Deployment
      name: kavita
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value: 
          name: library
          nfs:
            server: 192.168.1.3
            path: /Library
            readOnly: true

