apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Set the hostname for the Kavita ingress
  - target:
      version: v1
      kind: Ingress
      name: kavita
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kavita.local
      - op: add
        path: /spec/rules/-
        value:
          host: kavita.qed.fyi
          http:
            paths:
              - path: /
                backend:
                  service:
                    name: kavita
                    port:
                      name: http
                pathType: Prefix

  # Set the amount of storage to use for Kavita in its PVC
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: kavita
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi

  # Set the location of the library's volume in the Deployment
  - target:
      version: v1
      kind: Deployment
      name: kavita
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value: 
          name: library
          nfs:
            server: 192.168.1.5
            path: /Library
            readOnly: true

  # Configure the SMTP properties for KavitaEmail
  - target:
      version: v1
      kind: ConfigMap
      name: kavita-email
    patch: |-
      - op: replace
        path: /data
        value:
          appsettings.json: |
            {
                "TokenKey": "super ssdfasdfecret unguessable key",
                "Serilog": {
                  "Using":  [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
                  "MinimumLevel": "Debug",
                  "WriteTo": [
                    {
                      "Name": "Console",
                      "Args": {
                        "outputTemplate": "[KavitaEmail] [{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {ThreadId}] [{Level}] {SourceContext} {Message:lj}{NewLine}{Exception}"
                      }
                    },
                    { "Name": "File", "Args": {
                        "path": "config/logs/kavitaemail.log",
                        "outputTemplate": "[KavitaEmail] [{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {ThreadId}] [{Level}] {SourceContext} {Message:lj}{NewLine}{Exception}"
                      }
                    },
                    { "Name": "Seq", "Args": { "serverUrl": "http://localhost:5341", "apiKey": "" } }
                  ],
                  "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
                  "Destructure": [
                    { "Name": "ToMaximumDepth", "Args": { "maximumDestructuringDepth": 4 } },
                    { "Name": "ToMaximumStringLength", "Args": { "maximumStringLength": 100 } },
                    { "Name": "ToMaximumCollectionCount", "Args": { "maximumCollectionCount": 10 } }
                  ],
                  "Properties": {
                    "Application": "KavitaEmail"
                  }
                },
                "SMTP": {
                  "Host": "passw0rd.org",
                  "Port": 25,
                  "UserName": "",
                  "Password": "",
                  "SenderAddress": "kavita@passw0rd.org",
                  "SenderDisplayName": "Kavita Admin",
                  "AllowSendTo": true,
                  "SizeLimit": 26214400
                }
            }

